name: PR check 

on:
  pull_request:
    branches: 
    - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
    - run: npm i --unsafe-perm
    - run: npm run build --if-present


# name: PR check 

# on:
#   pull_request:
#     branches: 
#     - main

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     env:
#       CI: true

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: Install dependencies
#     - run: npm i --unsafe-perm
#     - run: npm run build --if-present
#     # - run: npm test
#       #   CI: true